name: test-pull-request

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  build-and-zip-mcp-server:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Make build script executable
        run: chmod +x ./Unity-MCP-Server/build-all.sh

      - name: Build executables for all platforms
        shell: bash {0}
        run: cd Unity-MCP-Server && ./build-all.sh Release

  # test-unity-mcp-common:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '9.0.x'

  #     - name: Restore dependencies
  #       working-directory: Unity-MCP-Plugin/Assets/root/Unity-MCP-Common
  #       run: dotnet restore

  #     - name: Build
  #       working-directory: Unity-MCP-Plugin/Assets/root/Unity-MCP-Common
  #       run: dotnet build --no-restore --configuration Release

  #     - name: Test
  #       working-directory: Unity-MCP-Plugin/Assets/root/Unity-MCP-Common
  #       run: dotnet test --no-build --verbosity normal --configuration Release

  # --- UNITY TESTS ---
  # -------------------

  # --- EDIT MODE ---

  test-unity-2022-3-69f1-editmode:
    needs: [build-and-zip-mcp-server]
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: "./Unity-MCP-Plugin"
      unityVersion: "2022.3.69f1"
      testMode: "editmode"
    secrets: inherit

  test-unity-2023-2-22f1-editmode:
    needs: [build-and-zip-mcp-server]
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: "./Unity-MCP-Plugin"
      unityVersion: "2023.2.22f1"
      testMode: "editmode"
    secrets: inherit

  test-unity-6000-3-1f1-editmode:
    needs: [build-and-zip-mcp-server]
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: "./Unity-MCP-Plugin"
      unityVersion: "6000.3.1f1"
      testMode: "editmode"
    secrets: inherit

  # --- PLAY MODE ---

  # test-unity-2022-3-69f1-playmode:
  #   needs: [build-and-zip-mcp-server]
  #   uses: ./.github/workflows/test_unity_plugin.yml
  #   with:
  #     projectPath: './Unity-MCP-Plugin'
  #     unityVersion: '2022.3.69f1'
  #     testMode: 'playmode'
  #   secrets: inherit

  # test-unity-2023-2-22f1-playmode:
  #   needs: [build-and-zip-mcp-server]
  #   uses: ./.github/workflows/test_unity_plugin.yml
  #   with:
  #     projectPath: './Unity-MCP-Plugin'
  #     unityVersion: '2023.2.22f1'
  #     testMode: 'playmode'
  #   secrets: inherit

  # test-unity-6000-3-1f1-playmode:
  #   needs: [build-and-zip-mcp-server]
  #   uses: ./.github/workflows/test_unity_plugin.yml
  #   with:
  #     projectPath: './Unity-MCP-Plugin'
  #     unityVersion: '6000.3.1f1'
  #     testMode: 'playmode'
  #   secrets: inherit

  # --- STANDALONE ---

  test-unity-2022-3-69f1-standalone:
    needs: [build-and-zip-mcp-server]
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: "./Unity-MCP-Plugin"
      unityVersion: "2022.3.69f1"
      testMode: "standalone"
    secrets: inherit

  test-unity-2023-2-22f1-standalone:
    needs: [build-and-zip-mcp-server]
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: "./Unity-MCP-Plugin"
      unityVersion: "2023.2.22f1"
      testMode: "standalone"
    secrets: inherit

  test-unity-6000-3-1f1-standalone:
    needs: [build-and-zip-mcp-server]
    uses: ./.github/workflows/test_unity_plugin.yml
    with:
      projectPath: "./Unity-MCP-Plugin"
      unityVersion: "6000.3.1f1"
      testMode: "standalone"
    secrets: inherit

  # -------------------
